import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName: "MEDIGRAM",
    tagline: "Your trusted health guide",
    howAreYouFeeling: "How are you feeling today?",
    tapToTell: "Tap the button and tell me",
    listening: "Listening to your voice...",
    voiceActive: "Voice Assistant Active",
    checkSymptoms: "Check Symptoms",
    findClinic: "Find Clinic",
    myFamily: "My Family",
    callAsha: "Call ASHA Worker",
    govtSchemes: "Govt. Schemes",
    healthRecords: "Health Records",
    stayHydratedTitle: "Stay Hydrated Today",
    stayHydratedBody: "It is very hot outside. Drink plenty of clean water to stay healthy and active.",
    sos: "SOS",
    emergencyHelp: "Emergency Help",
    home: "Home",
    voice: "Voice AI",
    map: "Clinics & Map",
    family: "Family Health",
    symptomsTab: "Symptom Triage",
    online: "Online",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    mobileView: "App Mode",
    webView: "Desktop Mode",
    doctorConsult: "Consult Doctor",
    nearbyHospitals: "Nearby Health Centers",
    emergencyCall108: "Call 108 Ambulance",
    ashaWorkerName: "Sunita Devi",
    ashaTitle: "Your ASHA Worker",
    ashaDistrict: "Rampur Block Health Care",
    callNow: "Call Now",
    chatMessage: "Send Message",
    selectSymptomBody: "Select body area or symptoms:",
    evaluateRisk: "Assess My Risk",
    riskLow: "Low Risk - Home Care",
    riskModerate: "Moderate Risk - Consult PHC",
    riskHigh: "High Risk - Immediate Emergency",
    pillTracker: "Medication Reminders",
    vaccinePassport: "Family Vaccine Records",
    abhaCard: "Digital ABHA Health ID",
    appointmentBooked: "Appointment Confirmed!",
    cancel: "Cancel",
    confirm: "Confirm",
    searchPlaceholder: "Search clinics, doctors, remedies...",
    reservePharmacy: "Reserve at this Pharmacy",
    govtApproved: "Govt Approved",
    nextDue: "Next Due",
    polioDrops: "Polio Drops (OPV 3)",
    dueDate: "15 Oct 2023",
    setReminder: "Set Reminder",
    vaccinationSchedule: "Vaccination Schedule",
    tracker: "Tracker",
    history: "History",
    reports: "Reports",
    searchMedicines: "Search medicines here...",
  },
  hi: {
    appName: "मेडिग्राम",
    tagline: "आपका विश्वस्त स्वास्थ्य मार्गदर्शक",
    howAreYouFeeling: "आज आप कैसा महसूस कर रहे हैं?",
    tapToTell: "बटन दबाएं और मुझे बताएं",
    listening: "आपकी आवाज सुनी जा रही है...",
    voiceActive: "वॉयस असिस्टेंट सक्रिय है",
    checkSymptoms: "लक्षण जांचें",
    findClinic: "अस्पताल खोजें",
    myFamily: "मेरा परिवार",
    callAsha: "आशा कार्यकर्ता को कॉल करें",
    govtSchemes: "सरकारी योजनाएं",
    healthRecords: "स्वास्थ्य रिकॉर्ड",
    stayHydratedTitle: "आज भरपूर पानी पीएं",
    stayHydratedBody: "आज बहुत गर्मी है। स्वस्थ और ऊर्जावान रहने के लिए भरपूर साफ पानी पीएं।",
    sos: "आपतकाल (SOS)",
    emergencyHelp: "आपतकालीन सहायता",
    home: "होम",
    voice: "वॉयस एआई",
    map: "क्लीनिक और नक्शा",
    family: "परिवार स्वास्थ्य",
    symptomsTab: "लक्षण जांच",
    online: "ऑनलाइन",
    language: "भाषा",
    darkMode: "डार्क मोड",
    lightMode: "लाइट मोड",
    mobileView: "ऐप मोड",
    webView: "डेस्कटॉप मोड",
    doctorConsult: "डॉक्टर से परामर्श",
    nearbyHospitals: "निकटतम स्वास्थ्य केंद्र",
    emergencyCall108: "108 एम्बुलेंस को कॉल करें",
    ashaWorkerName: "सुनीता देवी",
    ashaTitle: "आपकी आशा कार्यकर्ता",
    ashaDistrict: "रामपुर ब्लॉक स्वास्थ्य केंद्र",
    callNow: "अभी कॉल करें",
    chatMessage: "संदेश भेजें",
    selectSymptomBody: "शारीरिक अंग या लक्षण चुनें:",
    evaluateRisk: "जोखिम का आकलन करें",
    riskLow: "कम जोखिम - घरेलू देखभाल",
    riskModerate: "मध्यम जोखिम - प्राथमिक स्वास्थ्य केंद्र जाएं",
    riskHigh: "उच्च जोखिम - तुरंत अस्पताल जाएं",
    pillTracker: "दवाई की खुराक रिमाइंडर",
    vaccinePassport: "परिवार का टीकाकरण रिकॉर्ड",
    abhaCard: "डिजिटल आभा (ABHA) कार्ड",
    appointmentBooked: "अपॉइंटमेंट की पुष्टि हो गई!",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    searchPlaceholder: "क्लीनिक, डॉक्टर या बीमारी खोजें...",
    reservePharmacy: "इस मेडिकल स्टोर से बुक करें",
    govtApproved: "सरकारी मान्यता प्राप्त",
    nextDue: "अगली खुराक",
    polioDrops: "पोलियो ड्रॉप्स (OPV 3)",
    dueDate: "15 अक्टूबर 2023",
    setReminder: "रिमाइंडर लगाएं",
    vaccinationSchedule: "टीकाकरण समय-सारणी",
    tracker: "ट्रैकर",
    history: "इतिहास",
    reports: "रिपोर्ट्स",
    searchMedicines: "यहां दवाइयां खोजें...",
  },
  mr: {
    appName: "मेडिग्राम",
    tagline: "तुमचा विश्वासू आरोग्य मार्गदर्शक",
    howAreYouFeeling: "आज तुम्हाला कसे वाटत आहे?",
    tapToTell: "बटण दाबा आणि मला सांगा",
    listening: "तुमचा आवाज ऐकला जात आहे...",
    voiceActive: "व्हॉइस असिस्टंट सक्रिय आहे",
    checkSymptoms: "लक्षणे तपासा",
    findClinic: "दवाखाना शोधा",
    myFamily: "माझे कुटुंब",
    callAsha: "आशा ताईंना कॉल करा",
    govtSchemes: "सरकारी योजना",
    healthRecords: "आरोग्य नोंदी",
    stayHydratedTitle: "आज भरपूर पाणी प्या",
    stayHydratedBody: "आज खूप उकाडा आहे. निरोगी राहण्यासाठी भरपूर स्वच्छ पाणी प्या.",
    sos: "आपत्कालीन (SOS)",
    emergencyHelp: "आपत्कालीन मदत",
    home: "मुख्य पृष्ठ",
    voice: "व्हॉइस एआय",
    map: "दवाखाने व नकाशे",
    family: "कुटुंब आरोग्य",
    symptomsTab: "लक्षण निदान",
    online: "ऑनलाइन",
    language: "भाषा",
    darkMode: "डार्क मोड",
    lightMode: "लाइट मोड",
    mobileView: "अ‍ॅप मोड",
    webView: "डेस्कटॉप मोड",
    doctorConsult: "डॉक्टरांचा सल्ला घ्या",
    nearbyHospitals: "जवळची आरोग्य केंद्रे",
    emergencyCall108: "108 अ‍ॅम्ब्युलन्स कॉल करा",
    ashaWorkerName: "सुनिता देवी",
    ashaTitle: "तुमच्या आशा ताई",
    ashaDistrict: "रामपूर प्राथमिक आरोग्य केंद्र",
    callNow: "आत्ताच कॉल करा",
    chatMessage: "संदेश पाठवा",
    selectSymptomBody: "शरीराचा भाग किंवा लक्षणे निवडा:",
    evaluateRisk: "धोका तपासा",
    riskLow: "कमी धोका - घरीच काळजी घ्या",
    riskModerate: "मध्यम धोका - आरोग्य केंद्रात जा",
    riskHigh: "गंभीर - त्वरित आपत्कालीन मदत घ्या",
    pillTracker: "गोळ्यांची आठवण",
    vaccinePassport: "लसीकरण नोंदणी",
    abhaCard: "डिजिटल आभा (ABHA) कार्ड",
    appointmentBooked: "अपॉइंटमेंट नक्की झाली!",
    cancel: "रद्द करा",
    confirm: "नक्की करा",
    searchPlaceholder: "दवाखाना, डॉक्टर किंवा औषध शोधा...",
    reservePharmacy: "या मेडिकल स्टोअरमधून रिझर्व्ह करा",
    govtApproved: "शासकीय मान्यताप्राप्त",
    nextDue: "पुढील डोस",
    polioDrops: "पोलिओ ड्रॉप्स (OPV 3)",
    dueDate: "15 ऑक्टोबर 2023",
    setReminder: "स्मरणपत्र लावा",
    vaccinationSchedule: "लसीकरण वेळापत्रक",
    tracker: "ट्रॅकर",
    history: "इतिहास",
    reports: "अहवाल (रिपोर्ट्स)",
    searchMedicines: "इथे औषधे शोधा...",
  },
  ta: {
    appName: "மெடிகிராம்",
    tagline: "உங்கள் நம்பிக்கையான சுகாதார வழிகாட்டி",
    howAreYouFeeling: "இன்று நீங்கள் எப்படி உணர்கிறீர்கள்?",
    tapToTell: "பொத்தானைத் தொட்டு என்னிடம் சொல்லுங்கள்",
    listening: "உங்கள் குரலைக் கேட்கிறது...",
    voiceActive: "குரல் உதவியாளர் செயல்படுகிறது",
    checkSymptoms: "அறிகுறிகளைச் சரிபார்க்கவும்",
    findClinic: "மருத்துவமனையைக் கண்டறியவும்",
    myFamily: "என் குடும்பம்",
    callAsha: "ஆஷா ஊழியரை அழைக்கவும்",
    govtSchemes: "அரசு திட்டங்கள்",
    healthRecords: "சுகாதார பதிவுகள்",
    stayHydratedTitle: "நிறைய தண்ணீர் குடியுங்கள்",
    stayHydratedBody: "இன்று வெயில் அதிகம். ஆரோக்கியமாக இருக்க போதுமான தண்ணீர் குடியுங்கள்.",
    sos: "அவசரம் (SOS)",
    emergencyHelp: "அவசர உதவி",
    home: "முகப்பு",
    voice: "குரல் AI",
    map: "மருத்துவமனை வரைபடம்",
    family: "குடும்ப சுகாதாரம்",
    symptomsTab: "அறிகுறி பகுப்பாய்வு",
    online: "ஆன்லைன்",
    language: "மொழி",
    darkMode: "டார்க் மோட்",
    lightMode: "லைட் மோட்",
    mobileView: "ஆப் பயன்முறை",
    webView: "டெஸ்க்டாப் பயன்முறை",
    doctorConsult: "மருத்துவ ஆலோசனை",
    nearbyHospitals: "அருகிலுள்ள சுகாதார மையங்கள்",
    emergencyCall108: "108 ஆம்புலன்ஸ் அழைக்கவும்",
    ashaWorkerName: "சுனிதா தேவி",
    ashaTitle: "உங்கள் ஆஷா ஊழியர்",
    ashaDistrict: "ராம்பூர் சுகாதார மையம்",
    callNow: "இப்போது அழைக்கவும்",
    chatMessage: "செய்தி அனுப்பவும்",
    selectSymptomBody: "உடல் பகுதி அல்லது அறிகுறிகளைத் தேர்ந்தெடுக்கவும்:",
    evaluateRisk: "ஆபத்தை மதிப்பிடவும்",
    riskLow: "குறைந்த ஆபத்து - வீட்டில் பராமரிப்பு",
    riskModerate: "மிதமான ஆபத்து - மருத்துவமனைக்குச் செல்லவும்",
    riskHigh: "அதிக ஆபத்து - உடனடி அவசர சிகிச்சை",
    pillTracker: "மருந்து நினைவூட்டல்",
    vaccinePassport: "தடுப்பூசி பதிவு",
    abhaCard: "டிஜிட்டல் ABHA கார்டு",
    appointmentBooked: "முன்பதிவு உறுதி செய்யப்பட்டது!",
    cancel: "ரத்து செய்",
    confirm: "உறுதி செய்",
    searchPlaceholder: "மருத்துவமனை, மருத்துவர் அல்லது மருந்து தேடுங்கள்...",
    reservePharmacy: "மருந்தகத்தில் முன்பதிவு செய்க",
    govtApproved: "அரசு அங்கீகாரம் பெற்றது",
    nextDue: "அடுத்த தவணை",
    polioDrops: "போலியோ சொட்டு மருந்து (OPV 3)",
    dueDate: "15 அக்டோபர் 2023",
    setReminder: "நினைவூட்டல் அமை",
    vaccinationSchedule: "தடுப்பூசி அட்டவணை",
    tracker: "டிராக்கர்",
    history: "வரலாறு",
    reports: "அறிக்கைகள்",
    searchMedicines: "மருந்துகளை இங்கே தேடுங்கள்...",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
